
action_file.yml  config_file.yml  crontab.txt
[docker@kfdcel01 ~]$ cat curator/config/config_file.yml
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts: ["kfdcel02.hlcl.com",
      "kfdcel03.hlcl.com",
      "kfdcel04.hlcl.com",
      "kfdcel05.hlcl.com"]
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth:
  timeout: ${TIMEOUT:120}
  master_only: false
logging:
  loglevel: INFO
  logfile:
  logformat: default
  #blacklist: ['elasticsearch', 'urllib3']
[docker@kfdcel01 ~]$
